version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format='dta.gz'
    outputs:
      highly_sensitive:
        cohort: output/input.dta.gz
    ### NOTE if using Stata to analyse the main input file(s) please use --output-format='dta.gz' as above, 
    ### and open the file with 'gzuse' in Stata (http://fmwww.bc.edu/RePEc/bocode/g/gzsave.html)
    ### else use --output-format='csv.gz' 

  run_model:
    run: stata-mp:latest analysis/model.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/model.log

